---
abstract: 'Lookup for country names given the TLD code (¡en Español!)'
author:
  - 'David Moreno <david@axiombox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Domain-ES-ccTLD
no_index:
  directory:
    - t
    - inc
requires:
  Modern::Perl: 1.03
  Test::More: 0
version: 0.05
